version: '3.3'

services:

  db:
    container_name: autotrade_db
    image: postgres:14
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always
    ports:
      - 5432:5432
    networks:
      - tg_bot
    volumes:
      - ./postgres:/var/lib/postgresql
    env_file:
      - ".env"

  app_redis:
    container_name: ${PROJECT_SLUG}_redis
    networks:
      - tg_bot
    image: redis:5.0.0
    command: "redis-server"


  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m main
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    networks:
      - tg_bot
    environment:
      - PYTHONUNBUFFERED=1

networks:
  tg_bot:
    driver: bridge
